name: Long Running Action

on:
  pull_request:
    types: [opened, synchronized]

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run for 2 minutes
        run: |
          sleep 120
  
  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run for 2 minutes
        run: |
          sleep 120
